### ISSUE TITLE
Add more thorough documentation

### ISSUE THREAD

**Issue by nickevansuk** [openactive/openactive-test-suite#20]
Feedback from imin: "Add more thorough documentation. Especially as there's lots of potentially non-obvious design decisions in here. The broker is very simple (which is great!) but the integration tests are more complicated. So I would highly recommend fleshing out the documentation there. Summary of how exactly it works as well as "why?" questions. This is a great start: https://github.com/openactive/openactive-test-suite/blob/master/packages/openactive-integration-tests/DEVELOPMENT.md but it's written rather hastily"

**Comment by henryaddison** [comment]
For inspiration see this from the validator library https://github.com/openactive/data-model-validator/blob/master/CONTRIBUTING.md

**Comment by thill-odi** [comment]
Given that we won't (at least in the immediate future) be building the full scope of the testing framework, the priorities for this task have shifted, as discussed 1 May 2020. The new priorities are:

1. To outline all the information needed to inform an accurate delivery roadmap of the testing framework at full scope. This will involve reviewing the Revised Requirements tab of the MoSCoW spreadsheet: https://docs.google.com/spreadsheets/d/1TEjBpxktx-j3O1DU6zELhB5BNrW9KF1-JPQmxtRCXjg/edit#gid=149217759 and providing:

a) A short overview of each epic (e.g. 'Test Suite - Feed Listener', 'Framework Improvements'), indicating general considerations, concerns, points where there is a lack of clarity, and known unknowns. This may take paragraph form or bullet points as is most appropriate, but must provide a high-level summary of the problem space.

b) A minimum of one bullet point or sentence per epic line-item, specifying in more detail the challenges and possible complexities involved in each.

This work should initially be timeboxed to 0.5 days so that the feasibility of completing the task in an additional 1d can be assessed.

Should the work be completed within the 1.5d timebox, a secondary documentation need is to provide instructions on how to add tests to the suite in its current state.

**Comment by nickevansuk** [comment]
Please see the rules spreadsheet on which the estimates were based linked below. I've included both a snapshot at the point in time we did the estimates and the latest copy. The latter provides additional clarity, and might be useful to reference to reduce the need for a clarification call, if some of the details are hazy.

- [Copy from March 30](https://docs.google.com/spreadsheets/d/1T2ik56JbFpmeJOGWuSpGRqidPzfgKfQn8lLrJIuOkCQ/edit#gid=1483528703) 
- [Latest](https://docs.google.com/spreadsheets/d/1T2ik56JbFpmeJOGWuSpGRqidPzfgKfQn8lLrJIuOkCQ/edit#gid=1383644278) (note column G references https://www.openactive.io/test-interface/)

**Comment by nickevansuk** [comment]
More extensive documentation has since been added to the protect, including updating https://github.com/openactive/openactive-test-suite/blob/master/packages/openactive-integration-tests/DEVELOPMENT.md and the addition of https://github.com/openactive/openactive-test-suite/blob/master/packages/openactive-integration-tests/ARCHITECTURE.md
