### ISSUE TITLE
Allow user to configure which opportunity types are supported

### ISSUE THREAD

**Issue by thtg88** [openactive/openactive-test-suite#51]
See https://github.com/openactive/openactive-test-suite/tree/master/packages/openactive-integration-tests/test/features#testing-scope

> Additionally, an array of bookable opportunity types can be configured, to indicate which types the implementation is expected to support

Allow a user to specify which of the 5 opportunity types should be supported and update tests to run variants of each test for each of those supported opportunities.

How the user can configure the available option types must be documented.

As in https://github.com/openactive/openactive-test-suite/issues/11#issuecomment-603793885, the config format can be:
```json
  "opportunity-types": {
    "sessions": true,
    "facilities": true,
    "events": false,
    "headline-events": false,
    "courses": false
  }
```

Once #59  as been done then can determine all the valid feed types offered by the booking system under test. It has been decided that if a type is configured to be on but not available in the list of valid feed types then there should be a test failure stating this is not valid.

Depends on:
- Re-organize folder structure, including logger changes [#57]
- Add user-defined configuration to test suite [#58]
- Will use very similar approach to per-feature config [#50] and random/controlled config [#52]

Related:

- Be aware of #53 to have tests run for 1, 2, and 3 items of each type
- Be aware of #54 to have tests run for pairs of items of different types

Subtasks:

- [ ] Add option to configuration to set the supported types
- [ ] Run tests multiple times using events of each of the configured types
- [ ] Add test failure for types turned on which are not available in feeds
- [ ] Document how the user can configure which types are supported

**Comment by henryaddison** [comment]
See also https://github.com/openactive/openactive-test-suite/issues/11#issuecomment-603793885

**Comment by ylt** [comment]
As defined in #11, this will be defined in config in the format of:
```json
  "opportunity-types": {
    "sessions": true,
    "facilities": true,
    "events": false,
    "headline-events": false,
    "courses": false
  }
```

In terms of interacting with the test suite, this will probably be wrapped with a helper in order to get a list of all the enabled types.

---

There is also #59 - as part of this we'll be able to determine all the valid feed types, so this is another option.

This opens up some questions about how the toggles above interact with the config derived from the feed. All case combinations:
 - If enabled, and it's available in the feed: ✅ run tests
 - if enabled, and it's not available in the feed: ❓???
 - if disabled, and it's available in the feed: ❌ don't run tests, however do we print out an info message saying that it's available and not being tested?
 - if disabled, and it's not available in the feed: ❌ don't run tests

---

This particular case is the interesting one:
 - if enabled, and it's not available in the feed

As far as I can determine, the following options are available:
- Fail the test stating that it's not valid (cons: this doesn't allow defaulting things to enabled)
- Put a pending/soft test failure (cons: logger/reporter doesn't have support for pending tests)
- Skip entirely (a.k.a. "only try tests based on feeds in the dataset site" as detailed, cons: may miss that an opportunity type hasn't been tested).

I think the agreement during meeting was the "skip entirely" approach.

**Comment by nickevansuk** [comment]
Decision:
- Fail the test stating that it's not valid (cons: this doesn't allow defaulting things to enabled)

**Comment by nickevansuk** [comment]
Included in test.json
