### ISSUE TITLE
Allow user to specify whether to run random, controlled or both types of tests globally

### ISSUE THREAD

**Issue by thtg88** [openactive/openactive-test-suite#52]
See "Types of test" at https://github.com/openactive/openactive-test-suite/tree/master/packages/openactive-integration-tests/test/features#testing-scope

In random mode, the test will use a random event found in the feed. In controlled mode, the test will create events it needs Controlled tests may allow for more thorough testing but not every API implementation will be able to support the extra API endpoints needed to allow for it. Therefore need to provide a way to allow the user to turn each test mode on or off on a global basis.

How the user can configure the test modes must be documented.

Depends on:
- Re-organize folder structure, including logger changes [#57]
- Add user-defined configuration to test suite [#58]
- Should be an simple extension of #50 to run only random or non-random or both (like implemented or not-implemented).

Subtasks:
- [ ] Add global option to configuration to set the test modes
- [ ] Determine which sets of test events to try with the test flows based on configuration (e.g. just the randomly found events, just the created events, or both)
- [ ] How the user can configure the test modes must be documented.

**Comment by henryaddison** [comment]
Should be an simple extension of https://github.com/openactive/openactive-test-suite/issues/50 to run only random or non-random or both (like implemented or not-implemented).

**Comment by ylt** [comment]
This is a global setting.

There is currently a `useRandomOpportunities` setting, this however only prevents deleting events rather than determining which tests to run.

Work needs doing to make this option used to determine which test suites need running.

**Comment by henryaddison** [comment]
Logic for picking random events should go in microservice, not the test suite (e.g. test suite just asks microservice for the event called foo and it will know how to do that).

**Comment by henryaddison** [comment]
@nickevansuk Do we need a both option for this or just random and just controlled options?

**Comment by nickevansuk** [comment]
Suggest one or the other

**Comment by nickevansuk** [comment]
Additionally suggest a further improvement for the "controlled" version: just pass the [case `name`](https://github.com/openactive/openactive-test-suite/issues/77) to the "createOpportunity" test harness endpoint, instead of the full OpenActive model for the event (so just the `name` rather than the `event` from [here](https://github.com/openactive/openactive-test-suite/blob/master/packages/openactive-integration-tests/test/flows/book-only/book-only-success/book-free-test.js)).

This means they'd just need to create a switch statement inside the test endpoint to create the relevant type of event in the relevant state, instead of building a parser for an event in the OpenActive opportunity model, which they don't need anywhere else.

Especially as most elements of the parser would only be used once per test (as each test covers different properties), and otherwise the parser itself would need testing.

**Comment by nickevansuk** [comment]
`useRandomOpportunities` config setting achieves this by utilising the standard [test interface](https://openactive.io/test-interface/). Only allows running controlled or random, not both, for simplicity. Both can be achieved by simply running the test suite twice, as per: https://github.com/openactive/openactive-test-suite/blob/a87da46a27c1af0d7a9bda939858d01b601b54fd/publish-example-output.sh#L31-L45
