### ISSUE TITLE
Run each test using 1, 2 and 3 items as the test data

### ISSUE THREAD

**Issue by thtg88** [openactive/openactive-test-suite#53]
See https://github.com/openactive/openactive-test-suite/tree/master/packages/openactive-integration-tests/test/features#testing-scope

> All tests are run for the following:
> - 1, 2 and 3 order items of each configured type. Duplicating the defined template in the test.

It is not enough just to check that the API behaves when there is only a single order item. Instead there should be tests cases verifying the implementation when there are 1, 2 and 3 order items (all of the same opportunity type). This should be repeated for each available opportunity type.

To get random events will need to get a sample without replacement (rather than getting single events multiple times) to avoid re-using same event. And for creating events multiple times will need to use a template or something like faker to avoid repeating data which should be unique.

Will need updating the state to pass multiple events at a time through the flow (NB a single event is an array of one item).

NB not every test will make sense with using multiple test events at once.

Depends on:
- Supporting multiple types of event [#51]

Related:

- Be aware of #54 to have tests run for pairs of items of different types

Subtasks:

- [ ] When running each test, use arrays of size 1, 2 and 3 as the set of test events for the test

**Comment by henryaddison** [comment]
Re-use criteria for random events (i.e. sample without replacement rather than getting single events multiple times to avoid re-using same event) or template for creating events multiple times (taking care to avoid repeating data which should be different, e.g. use faker).

Will need updating the state to pass multiple events at a time through the flow (NB a single event is an array of one item).

**Comment by nickevansuk** [comment]
A simple version of this is achieved with the FeatureHelper
