### ISSUE TITLE
Document use (and maintenance) of Shape Expressions in test suite

### ISSUE THREAD

**Issue by lukehesluke** [openactive/openactive-test-suite#562]
Make it clear that they can be ignored (and perhaps even consider removing them, despite them being best practice, due to the level of digital maturity of the sector)

**Comment by lukehesluke** [comment]
@nickevansuk would you be able to expand on your initial comment:

> Make it clear that they can be ignored (and perhaps even consider removing them, despite them being best practice, due to the level of digital maturity of the sector)

Could you give me an idea of what the most up to date thoughts are on this feature? Are we pushing it forwards with hopes to make random mode more stable or are we binning it? If it's not clear, would it be best to act as if we were pressing forwards with it for now?

**Comment by nickevansuk** [comment]
Perhaps what would be most helpful is:
- A flag in test suite's default.json that turns them on and off - so that they can be excluded from the responses, which simplifies test suite output; along with documentation of this
- Documentation of how to use them to generate test data (i.e. how to interpret them); also documentation of using a `switch` statement to generate test data (as [ref impl](https://github.com/openactive/OpenActive.Server.NET/blob/c909ec728e578a6c78a28d536f9ea516658b2edf/Examples/BookingSystem.AspNetCore/Stores/SessionStore.cs#L47) does)
- Documentation of how to update Shape Expressions to match the criteria

**Comment by lukehesluke** [comment]
Thanks @nickevansuk , great plan. These have been turned into the following issues:

* Toggleable flag: https://github.com/openactive/openactive-test-suite/issues/587
* <TODO>

**Comment by lukehesluke** [comment]
As all constituent parts have been elaborated into separate issues, I'm closing this issue
