### ISSUE TITLE
Travis CI script example

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#64]
A travis CI example script should be provided that starts the feed listener, then runs it against the .NET reference implementation

**Comment by ylt** [comment]
Is this necessarily to start the feed listener?

As discussed in calls, this could take a while to start, so starting it at the same time may not be an option. It may be necessary to host this somewhere. Of course this opens up the problem that the feed listener itself will have stale / out of date data after code changes to tbe rpde feed.

---

In order to have the test suite work when started at the same time as the feed listener, we'll probably need a few additional endpoints on the feed listener.
* Query ready status: determine whether it's ready
* Wait until ready: keep request open until it's ready
* Shutdown: once it's done, it'll need shutting down, easiest way is probably via a new endpoint (or perhaps we could achieve this by keeping track of the pid and sending a kill signal)

**Comment by henryaddison** [comment]
Decided approach:
start feed listener and wait for it to be ready before starting tests
ready means: wait for pagination to finish across all feeds

**Comment by nickevansuk** [comment]
https://github.com/openactive/openactive-test-suite/blob/master/simple-ci.sh
