### ISSUE TITLE
Add summary view of test output in markdown and CLI

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#79]
Worried about the number of tests being added might mean the user is overwhelmed with output

**Comment by ylt** [comment]
# Pre-requisites

- Logger output to use naming based on test filename, rather than the describes (allow associating to the test within reporter)
- Move logger initialisation into the test start helper, this ensures that tests will always be created
- Add helper methods to logger to set the details originally passed in constructor
- 

# Goal

- Describe at top level detail the detail of whether flows pass as a whole or not.
- Give a central hub of links for the user to view the markdown files to get insight on the statuses of individual tests.
- Stretch: indicate last successful describe block (which should indicate where the problems start)
- Stretch: a little breakdown alongside each (total number of number of passing, failing, validation errors within)

# Example

```bash
core	> opportunity-feed	> RPDE Opportunity Feed ✅ (10 passes, 0 failures, 5 warnings)
core	> dataset-site	> Dataset Site ✅ (10 passes, 0 failures, 5 warnings)
core	> availability-check	> Availability Checking ✅ (15 passes, 0 failures, 10 warnings)
cancellation	> customer-requested-cancellation	> Customer Requested Cancellation ❌ (5 passes, 15 failures, 5 warnings; C2, B, U failing)
```

**Comment by nickevansuk** [comment]
```
{
"category": {

},
"name": {
   "availability-check": "Availability Check"
},
"testName" : {

}
}
```

**Comment by nickevansuk** [comment]
en.json
```
{
  "core": "Core",
  "core|availability-check": "Availability Check",
  "core|availability-check|implemented|availability-confirmed": "Occupancy in C1 and C2 matches feed",
  "core|availability-check|not-implemented|feature-required-noop": "Feature required",
  "core|dataset-site": "Dataset Site",
  "core|dataset-site|implemented|dataset-site-jsonld-valid": "Dataset Site JSON-LD valid",
  "core|dataset-site|not-implemented|feature-required-noop": "Feature required",
  "payment": "Payment",
  "payment|simple-book-with-payment": "Simple Booking of paid opportunities",
  "payment|simple-book-with-payment|implemented|with-payment-property": "Successful booking with payment property",
  "payment|simple-book-with-payment|not-implemented|no-paid-bookable-sessions": "No paid bookable sessions"
}
```

Two questions:
1) Should the keys include `not-implemented` and `not-implemented`?
2) Will this work when the tests have the same name (e.g. "feature-required-noop" / "Feature required")?

**Comment by ylt** [comment]
Thanks a lot

1. no need for implemented / not-implemented
2. still to be determined, almost to the point where I'll be integrating this - will provide feedback once I know

**Comment by nickevansuk** [comment]
great, have removed implemented / not-implemented

No worries!

**Comment by nickevansuk** [comment]
Looks good!
